"""Renders the natural-language explanation block.

The section exists to make one thing easy: a reader deciding whether to trust a score gets
a sentence in their own language instead of a table of weighted metrics. It is therefore
printed *after* the deterministic report, never before it - the number and the evidence
stand on their own first, and the prose is an addition a reader can skip.

Two rules about the text itself:

**It is model output, so it is printed as plain text, never as markup.** Every other
renderer in this package follows that rule for evidence from third parties
(see :func:`packsafe_cli.display.layout._cell`); generated prose is a stronger case,
because unlike a package name or a URL it was written with no human reviewing it for
characters like ``[bold]``. ``Text`` is constructed without ``style`` and without markup
parsing, so a bracket sequence is a bracket sequence.

**The score is shown next to the prose.** The explanation echoes the score it describes,
but it is a paraphrase produced by something that cannot be checked against a formula. A
reader seeing ``94.7/100`` immediately above the paragraph can spot a paragraph about a
different number at a glance, which is the whole reason to print both.
"""

from __future__ import annotations

import unicodedata

from packsafe_core.explain import Explanation
from packsafe_core.models.result import AnalysisOutcome
from rich.console import Console
from rich.padding import Padding
from rich.text import Text

from .layout import section
from .theme import DECISION_STYLE, RISK_STYLE

# The model is told to write 2-4 sentences, but a model can ignore instructions. Past this
# the block stops being an explanation and starts being a document nobody asked for.
MAX_EXPLANATION_CHARS = 1200


def render_explanation(
    console: Console, outcome: AnalysisOutcome, explanation: Explanation
) -> None:
    """Prints the explanation and the score it is describing."""
    score = outcome.score

    section(console, "Why This Score")

    text = _wrap(explanation.explanation)
    # Plain Text, no markup: this string came from a model, not from a field we control.
    console.print(Padding(Text(text, style="white"), (0, 1, 0, 2)))

    console.print()
    _print_provenance(console, score, explanation)


def _print_provenance(console: Console, score, explanation: Explanation) -> None:
    """Shows which score was explained, and which model wrote the words.

    Two separate claims are on display. The score is PackSafe's own, deterministic and
    reproducible. The model is not - it is named so a reader who distrusts the prose can
    see that the paragraph came from a particular vendor's particular checkpoint, and can
    re-run ``analyze`` to check whether the number moves (it will not).
    """
    risk_style = RISK_STYLE.get(score.risk_level, "white")
    decision_style = DECISION_STYLE.get(score.decision, "white")

    headline = Text("  ")
    headline.append(f"{score.final_score:.0f}/100", style=f"bold {risk_style}")
    headline.append("  ", style="bright_black")
    headline.append(score.decision.value, style=decision_style)
    headline.append("  ·  explained by ", style="bright_black")
    headline.append(f"{explanation.provider}/{explanation.model}", style="bright_black")
    console.print(headline)

    console.print(
        Padding(
            Text(
                "Score computed by the PackSafe engine · wording generated by a language model",
                style="bright_black",
            ),
            (0, 1, 0, 2),
        )
    )


def _wrap(text: str) -> str:
    """Bounds the block, neutralizes control characters, and flattens to one line.

    Three separate defenses, in order:

    **Control characters are stripped.** This is the one that is not obvious. Rich escapes
    ``[bold]``-style markup, so a model cannot restyle the block - but a raw ANSI escape
    (``\\x1b[31m``) is not markup, it is a terminal instruction, and Rich passes it
    through untouched. Left alone, model output could move the cursor, clear the screen,
    or emit an OSC sequence that rewrites the window title or the clipboard. A string no
    human reviewed must never be able to drive the terminal, so the whole C0/C1 range
    goes, along with DEL.

    **It is flattened to one line.** Keeps a model that ignored its "no headings"
    instruction from breaking the section's alignment.

    **It is bounded.** A model asked for four sentences that returns four thousand words
    has stopped explaining and started making a document nobody asked for.
    """
    cleaned = _strip_control(text or "")
    cleaned = " ".join(cleaned.split())

    if not cleaned:
        return "The explanation service returned no text."
    if len(cleaned) <= MAX_EXPLANATION_CHARS:
        return cleaned
    return cleaned[: MAX_EXPLANATION_CHARS - 1].rstrip() + "…"


def _strip_control(text: str) -> str:
    """Removes terminal control characters, keeping newlines and tabs for the flatten pass."""
    return "".join(
        char
        for char in text
        if char in "\n\t" or not (unicodedata.category(char) == "Cc" or char == "\x7f")
    )